name: CI/CD

on:
  # Push on main and release tags
  push:
    branches:
      - 'main'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  # PR
  pull_request:
    branches:
      - 'main'

  # Manual trigger
  workflow_dispatch:
    inputs:
      version:
        required: false
        description: Extensions version
        type: string
      is_release:
        required: false
        description: Create Extensions Release
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Checkout main repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          repository: openremote/openremote
          path: openremote
          ref: master
          sparse-checkout: profile
          sparse-checkout-cone-mode: false

      - name: Set up JDK 21 and gradle cache
        id: java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Check if main repo
        id: is_main_repo
        run: |
          if [ $GITHUB_REPOSITORY == 'openremote/extensions' ]; then
            echo "value=true" >> $GITHUB_OUTPUT
          fi

      - name: Update openremoteVersion in gradle.properties
        if: ${{ github.event_name != 'pull_request' && inputs.version != '' }}
        run: sed -i "s/^openremoteVersion = .*/openremoteVersion = $VERSION/" gradle.properties
        env:
          VERSION: ${{ inputs.version }}

      - name: Run installDist
        timeout-minutes: 20
        run: ./gradlew installDist

      - name: Run integration tests
        if: ${{ inputs.is_release != true }}
        timeout-minutes: 20
        run: |
          # Run build
          # Make temp dir with 777 mask as docker seems to run as root
          mkdir -pm 777 tmp
          
          # Start the dev-testing stack
          docker compose -f openremote/profile/dev-testing.yml up -d --no-build
          
          ./gradlew test

      - name: Login to DockerHub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets._TEMP_DOCKERHUB_USER }}
          password: ${{ secrets._TEMP_DOCKERHUB_PASSWORD }}

      - name: Install QEMU
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'pull_request' }}
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          platforms: linux/amd64,linux/aarch64

      - name: Install Buildx
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'pull_request' }}
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0

      - name: Build develop image
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'pull_request' }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        timeout-minutes: 20
        with:
          context: deployment/build
          platforms: linux/amd64,linux/aarch64
          load: false
          push: true
          tags: openremote/manager:develop
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            QUALIFIER=develop
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Build manager image
        if: ${{ steps.is_main_repo.outputs.value && inputs.is_release == true }}
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
        timeout-minutes: 20
        with:
          context: deployment/build
          platforms: linux/amd64,linux/aarch64
          load: false
          push: true
          tags: |
            openremote/manager:${{ inputs.version }}
            openremote/manager:latest
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            QUALIFIER=latest
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Publish to Maven Sonatype
        if: ${{ steps.is_main_repo.outputs.value && github.event_name != 'pull_request' }}
        timeout-minutes: 20
        run: ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository -PsigningKey=$MAVEN_SIGNING_KEY -PsigningPassword=$MAVEN_SIGNING_PASSWORD -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD
        env:
          MAVEN_SIGNING_KEY: ${{ secrets._TEMP_MAVEN_SIGNING_KEY }}
          MAVEN_SIGNING_PASSWORD: ${{ secrets._TEMP_MAVEN_SIGNING_PASSWORD }}
          MAVEN_USERNAME: ${{ secrets._TEMP_MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets._TEMP_MAVEN_PASSWORD }}

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: '**/build/reports/tests'

      - name: Archive coverage report
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report
          path: '**/build/reports/jacoco/test/html'